
name: log-notate
dependencies:
- base
- text
- bytestring
- aeson
- mtl
- monad-control
- monad-logger
- http-conduit
- http-client
- hspec

library:
  source-dirs: src

executables:
  log-notate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:  
    - log-notate

tests:
  log-notate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - log-notate

